Title: Catan

define:
  - &width 1200
  - &height 800

Window:
  width: *width
  height: *height

Background:
  r: 38
  g: 38
  b: 38

Game:
  framerate: 120
  assets: "assets/assets.yaml"
  board: "assets/board.yaml"
