Title: Catan

define:
  - &width 1400
  - &height 800

Window:
  width: *width
  height: *height

Background:
  r: 38
  g: 38
  b: 38

Game:
  framerate: 120
  assets: "assets/assets.yaml"
  board: "assets/board.yaml"
  ui: "assets/ui/main.yaml"
  player_info: "assets/ui/player_info.yaml"
